using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using FluentAssertions;
using Mediax.Core;
using Mediax.Runtime;
using Mediax.Tests.Fixtures;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

namespace Mediax.Tests;

/// <summary>
/// Verifies the debuggability guarantees of code generated by Mediax.SourceGenerator:
///   1. Dispatch methods are named after the handler class (not Dispatch_0, Dispatch_1, ...)
///   2. Plumbing router methods carry [DebuggerStepThrough] so the debugger steps over them
///   3. MediaxDispatcher itself has NO [CompilerGenerated] — stays visible in "Just My Code"
///   4. MediaxStaticHandlers retains [CompilerGenerated] — pure plumbing, should be invisible
///   5. Stack traces produced by failing handlers contain the handler class name
/// </summary>
public sealed class DebugabilityTests : IDisposable
{
    private static readonly Type DispatcherType =
        typeof(MediaxDispatcher_DebugabilityTestMarker).Assembly
            .GetType("MediaxDispatcher", throwOnError: true)!;

    private static readonly Type StaticHandlersType =
        typeof(MediaxDispatcher_DebugabilityTestMarker).Assembly
            .GetType("MediaxStaticHandlers", throwOnError: true)!;

    private readonly IServiceProvider _sp;

    public DebugabilityTests()
    {
        _sp = TestServiceProvider.Create();
    }

    public void Dispose() { }

    // ── 1. Method naming ─────────────────────────────────────────────────────

    [Fact]
    public void GeneratedDispatcher_HasMethodNamedAfterHandler_NotIndex()
    {
        // Handler class is EchoQueryHandler → expected method name Dispatch_EchoQueryHandler
        DispatcherType.GetMethod(
            "Dispatch_EchoQueryHandler",
            BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
            .Should().NotBeNull("generated method should use handler class name, not numeric index");
    }

    [Fact]
    public void GeneratedDispatcher_HasNoIndexBasedDispatchMethod()
    {
        var methods = DispatcherType.GetMethods(
            BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public);

        methods.Should().NotContain(
            m => System.Text.RegularExpressions.Regex.IsMatch(m.Name, @"^Dispatch_\d+$", System.Text.RegularExpressions.RegexOptions.None, TimeSpan.FromSeconds(1)),
            "dispatch methods must be named after the handler, not their positional index");
    }

    [Fact]
    public void GeneratedDispatcher_AllHandlersHaveNamedMethods()
    {
        // Every [Handler]-annotated class in the test assembly should have a corresponding
        // Dispatch_{HandlerSimpleName} method on MediaxDispatcher.
        var handlerTypes = typeof(EchoQueryHandler).Assembly
            .GetTypes()
            .Where(t => t.GetCustomAttribute<HandlerAttribute>() != null);

        foreach (var handlerType in handlerTypes)
        {
            var expectedMethodName = "Dispatch_" + handlerType.Name;
            DispatcherType.GetMethod(
                expectedMethodName,
                BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
                .Should().NotBeNull($"MediaxDispatcher should have {expectedMethodName} for {handlerType.Name}");
        }
    }

    // ── 2. [DebuggerStepThrough] on plumbing ─────────────────────────────────

    [Theory]
    [InlineData("Dispatch")]     // the generic switch-router
    [InlineData("Stream")]       // the generic stream-router
    [InlineData("Publish")]      // the event publisher
    public void PlumbingMethods_HaveDebuggerStepThroughAttribute(string methodName)
    {
        var methods = DispatcherType
            .GetMethods(BindingFlags.Instance | BindingFlags.Public)
            .Where(m => string.Equals(m.Name, methodName, StringComparison.Ordinal)).ToList();

        methods.Should().NotBeEmpty($"MediaxDispatcher should have a public {methodName} method");
        foreach(var method in methods) 
        {
            var attributes = method.GetCustomAttributes<DebuggerStepThroughAttribute>(false);
            attributes.Should().NotBeEmpty($"{methodName} is routing plumbing and should carry [DebuggerStepThrough]");
        }
    }

    [Fact]
    public void NamedDispatchMethods_DoNotHaveDebuggerStepThrough()
    {
        // The actual Dispatch_EchoQueryHandler methods should NOT have DebuggerStepThrough —
        // those are the methods where developers want to set breakpoints.
        var namedDispatch = DispatcherType
            .GetMethods(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
            // Filter out _Cast, wrapper methods, and StateMachine generated classes.
            .Where(m => m.Name.StartsWith("Dispatch_", StringComparison.Ordinal) && !m.Name.EndsWith("_Cast", StringComparison.Ordinal) && !m.Name.EndsWith(">d", StringComparison.Ordinal));

        foreach (var method in namedDispatch)
        {
            var attributes = method.GetCustomAttributes<DebuggerStepThroughAttribute>(false);
            attributes.Should().BeEmpty($"{method.Name} should NOT have [DebuggerStepThrough] — it is a breakpoint target");
        }
    }

    [Fact]
    public void CastWrapperMethods_HaveDebuggerStepThrough()
    {
        var castMethods = DispatcherType
            .GetMethods(BindingFlags.Instance | BindingFlags.NonPublic)
            .Where(m => m.Name.EndsWith("_Cast", StringComparison.Ordinal));

        // Cast wrappers exist only for non-simple handlers; skip if none registered
        foreach (var method in castMethods)
        {
            var attributes = method.GetCustomAttributes<DebuggerStepThroughAttribute>(false);
            attributes.Should().NotBeEmpty($"{method.Name} is a type-erasure cast wrapper and should carry [DebuggerStepThrough]");
        }
    }

    // ── 3. [CompilerGenerated] absent from MediaxDispatcher ──────────────────

    [Fact]
    public void MediaxDispatcher_DoesNotHaveCompilerGeneratedAttribute()
    {
        DispatcherType.GetCustomAttribute<CompilerGeneratedAttribute>()
            .Should().BeNull(
                "MediaxDispatcher must NOT be marked [CompilerGenerated]: that attribute " +
                "triggers 'Just My Code' to hide the class, preventing breakpoints in Dispatch_* methods");
    }

    // ── 4. [CompilerGenerated] present on MediaxStaticHandlers ───────────────

    [Fact]
    public void MediaxStaticHandlers_HasCompilerGeneratedAttribute()
    {
        StaticHandlersType.GetCustomAttribute<CompilerGeneratedAttribute>()
            .Should().NotBeNull(
                "MediaxStaticHandlers IS pure plumbing (module initializer hooks) " +
                "and should remain hidden from the debugger via [CompilerGenerated]");
    }

    // ── 5. Stack trace readability ───────────────────────────────────────────

    [Fact]
    public async Task StackTrace_WhenHandlerThrows_ContainsHandlerClassName()
    {
        // ThrowingHandler throws InvalidOperationException — we capture the stack trace
        // and verify that the handler class name appears in it (not Dispatch_3 or similar).
        Exception? caught = null;
        try
        {
            var request = new ThrowingRequest("boom");
#pragma warning disable MX0001
            await request.Send(CancellationToken.None);
#pragma warning restore MX0001
        }
        catch (Exception ex)
        {
            caught = ex;
        }

        caught.Should().NotBeNull("ThrowingHandler should propagate the exception");
        caught!.StackTrace.Should().Contain(
            nameof(ThrowingHandler),
            "the handler class name must appear in the stack trace for debuggability");
    }
}

// ── Marker type so tests can locate the generated assembly ───────────────────

/// <summary>Marker — exists only to give DebugabilityTests a type in the right assembly.</summary>
internal sealed class MediaxDispatcher_DebugabilityTestMarker;

// ── Throwing handler for stack-trace test ────────────────────────────────────

public sealed record ThrowingRequest(string Message) : IQuery<string>;

[Handler(Lifetime = HandlerLifetime.Scoped)]
public sealed class ThrowingHandler : IHandler<ThrowingRequest, string>
{
    public ValueTask<Result<string>> Handle(ThrowingRequest request, CancellationToken ct)
        => throw new InvalidOperationException($"ThrowingHandler: {request.Message}");
}
